service: AlbertoFerroSLS
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverlessUser

  region: us-west-2

plugins:
  -serverless-s3-sync

custom:
  tableName: player-points
  s3Sync:
    - bucketName: serverless-albertoferro
      localDir: UploadData

functions:
  getUser:
    handler: lambdas/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true
#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
resources:
 Resources:
   BucketUpload:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: serverless-albertoferro
   MyDynamoDBTable:
     Type: AWS::DynamoDB::Table
     Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
